services:
  - type: web
    name: securechat-backend
    env: python
    buildCommand: ""
    startCommand: hypercorn server:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: MYSQL_HOST
        value: switchback.proxy.rlwy.net
      - key: MYSQL_PORT
        value: 37489
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: GdEfdzMJwMehXMnFSmliGbqviWHDHYiU
      - key: MYSQL_DB
        value: railway
